# Generated by Django 4.2.3 on 2023-08-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_inventoryorder_realized_date_shoporder_realized_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='realized_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_order_realized_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='realized_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_order_realized_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
