# Generated by Django 4.2.3 on 2023-08-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_inventoryorder_realized_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorder',
            name='items',
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='inventory_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.inventoryorder'),
        ),
    ]
